import type { Book } from "@/types";

// Duru's bookshelf. `thoughts` are in her own voice — the reason each book
// earned a place on the shelf. Colours are warm and earthy so the shelf reads
// like a real, printed collection; spine widths and heights vary per book.
// `id` also selects which botanical cover archetype is drawn (see Books.tsx).
export const books: Book[] = [
  {
    id: 1,
    title: "Dark Matter",
    author: "Blake Crouch",
    genre: "Fiction · Science Fiction",
    rating: 5,
    spineW: 40,
    h: 300,
    coverW: 194,
    spine: "#17203D",
    spineText: "#C9D2E8",
    c0: "#1F2A4D",
    accent: "#E9C46A",
    thoughts:
      "A physicist is kidnapped by another version of himself — and I couldn't put it down. It made me obsess over the roads not taken, the branching decisions, the parallel lives. Peak 'what if' science fiction, and a reminder that every choice quietly forks reality.",
  },
  {
    id: 2,
    title: "The Alchemist",
    author: "Paulo Coelho",
    genre: "Modern Fable",
    rating: 5,
    spineW: 30,
    h: 256,
    coverW: 172,
    spine: "#6E3E17",
    spineText: "#E8C9A6",
    c0: "#C8792F",
    accent: "#FDF3E3",
    thoughts:
      "The book that finds you at the right moment. Its idea of a Personal Legend — that the universe conspires to help you chase what you're meant to do — is exactly the mindset I packed when I set out from Izmir toward Europe.",
  },
  {
    id: 3,
    title: "Circe",
    author: "Madeline Miller",
    genre: "Mythology",
    rating: 5,
    spineW: 46,
    h: 284,
    coverW: 190,
    spine: "#4C2F49",
    spineText: "#E4CBDF",
    c0: "#7D5178",
    accent: "#F0DDEC",
    thoughts:
      "A goddess exiled to an island slowly builds a life on her own terms. I loved watching someone turn isolation into mastery. Miller's language is gorgeous, and Circe's quiet defiance stayed with me long after the last page.",
  },
  {
    id: 4,
    title: "A Game of Thrones",
    author: "George R.R. Martin",
    genre: "Epic Fantasy",
    rating: 5,
    spineW: 56,
    h: 296,
    coverW: 200,
    spine: "#241B10",
    spineText: "#D8C39B",
    c0: "#3A2E1C",
    accent: "#C9A66B",
    thoughts:
      "The series that taught me systems thinking before I had a name for it: dozens of players, competing incentives, consequences rippling for chapters. Complex, ruthless, endlessly re-readable world-building.",
  },
  {
    id: 5,
    title: "Dune",
    author: "Frank Herbert",
    genre: "Science Fiction",
    rating: 5,
    spineW: 48,
    h: 288,
    coverW: 196,
    spine: "#6E3B17",
    spineText: "#F0D2A8",
    c0: "#B4652A",
    accent: "#FBE6C9",
    thoughts:
      "Ecology, politics, religion and power fused into a single desert planet. As someone drawn to how large systems interact, Dune is the gold standard — every layer connects to another. 'Fear is the mind-killer' is still taped to my mental wall.",
  },
  {
    id: 6,
    title: "Sophie's World",
    author: "Jostein Gaarder",
    genre: "Philosophy",
    rating: 4,
    spineW: 50,
    h: 272,
    coverW: 184,
    spine: "#21403D",
    spineText: "#CFE0CB",
    c0: "#355E5B",
    accent: "#E7D8B0",
    thoughts:
      "A whole history of Western philosophy smuggled inside a mystery novel. It's the book that made me start asking why instead of just how — the same curiosity that still drives how I approach engineering.",
  },
  {
    id: 7,
    title: "Origin",
    author: "Dan Brown",
    genre: "Techno-Thriller",
    rating: 4,
    spineW: 38,
    h: 262,
    coverW: 176,
    spine: "#1B3A3D",
    spineText: "#CBE0DC",
    c0: "#2C5F63",
    accent: "#EAD9B0",
    thoughts:
      "Where do we come from, where are we going — asked through the lens of AI and science. A fast, fun thriller that also pokes at questions I think about a lot as I build software that grows a little more intelligent every year.",
  },
  {
    id: 8,
    title: "My Year of Rest and Relaxation",
    author: "Ottessa Moshfegh",
    genre: "Literary Fiction",
    rating: 4,
    spineW: 34,
    h: 258,
    coverW: 168,
    spine: "#8C8272",
    spineText: "#2C2419",
    c0: "#C9BCA8",
    accent: "#6B5B44",
    thoughts:
      "Bleak, sharp and weirdly funny — a woman decides to sleep through a year of her life. Completely different from my usual sci-fi, and that's exactly why I loved it: uncomfortable, honest, and impossible to look away from.",
  },
];
